version: '3.3'

services:

  skyhub-portal-mysql:
    image: mysql:5.6.42
    volumes: 
      - ../mysql/data/:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=skyhub123!!!
    networks:
      - skyhub-network
  skyhub-portal-portald:
    image: registry.gitlab.com/skyhuborg/skyhub:portald-develop
    restart: always
    environment:
      - database-host: "skyhub-portal-mysql"
      - database-password: "skyhub123!!!"
    ports:
       - "5432:5432"
    networks:
      - skyhub-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_etc:/etc/postgresql
  skyhub-portal-trackerd:
    image: registry.gitlab.com/skyhuborg/skyhub:trackerd-develop
    restart: always
    ports: 
     - 8081:8081
    networks:
      - skyhub-network
  skyhub-portal-ui:
    image: registry.gitlab.com/skyhuborg/portal-ui:develop
    restart: always
    ports: 
     - 8080:8080
    networks:
      - skyhub-network
networks:
  skyhub-network:
volumes:
  skyhub-portal-mysql:
